POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "admin@systers.xyz",
    "password": "123456"
}

GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHN5c3RlcnMueHl6IiwiaWF0IjoxNjk2MzQ5NjA1LCJleHAiOjE2OTYzNTMyMDUsInN1YiI6IjEifQ.oZ0tJmN3340W2hO0nWjSSkQ8epc1Dd3by3J5qEkz4Fk

GET http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzMzkwOSwiZXhwIjoxNjUwMjM3NTA5LCJzdWIiOiIyIn0.nS99u-MBatZHbexMUenwsGdS8oV55BIaGwI6PSP7BC8

GET http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzMzkwOSwiZXhwIjoxNjUwMjM3NTA5LCJzdWIiOiIyIn0.nS99u-MBatZHbexMUenwsGdS8oV55BIaGwI6PSP7BC8

PATCH http://localhost:8080/orders/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHN5c3RlcnMueHl6IiwiaWF0IjoxNjk2MjkwNjM3LCJleHAiOjE2OTYyOTQyMzcsInN1YiI6IjEifQ.Vn35zoSO9a6lwk3fmHtZcCifIjOruaJotG6pBlflEu4

{
    "status": "delivered",
    "dateProcessed": "2022-03-05 16:00"
}

POST http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHN5c3RlcnMueHl6IiwiaWF0IjoxNjk2OTAyMDYzLCJleHAiOjE2OTY5MDU2NjMsInN1YiI6IjEifQ.nT52gwvdhATSfLt0nQAw3S8xVFdlf_wBIgmMRV2aEZo
{
    "client": "Harry Potter",
    "products": [
        {
            "qty": 1,
            "product": {
                "id": 9,
                "name": "Ham and cheese sandwich",
                "price": 1000,
                "image": "https://raw.githubusercontent.com/ssinuco/burger-queen-api-mock/main/resources/images/sandwich.png",
                "type": "Breakfast",
                "dateEntry": "2022-03-05 15:14:10"
            }
        },
        {
            "qty": 1,
            "product": {
                "id": 1,
                "name": "American coffee",
                "price": 500,
                "image": "https://raw.githubusercontent.com/ssinuco/burger-queen-api-mock/main/resources/images/coffee.png",
                "type": "Beverages",
                "dateEntry": "2022-03-05 15:14:10"
            }
        }
    ],
    "status": "pending",
    "dataEntry": "2022-03-05 15:00"
}

DELETE http://localhost:8080/users/6 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im51dm91c3VhcmlvQGNvcnJlby5jb20iLCJpYXQiOjE2OTY2MDcwMTEsImV4cCI6MTY5NjYxMDYxMSwic3ViIjoiMTEifQ.fD3Sn_3bXj_5Upifqu1KNDJ-aff1Hjl7qJQ3Bhj7wJY